# we are going to perform all the task on the titanic dataset without using pipeline

In [8]:
import numpy as np 
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [21]:
df = pd.read_csv("train.csv")

we are using this dataset becouse we are familier with this dataset<br>
and it will be easy for us to understand.

In [19]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
526,527,1,2,"Ridsdale, Miss. Lucy",female,50.0,0,0,W./C. 14258,10.500,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.475,NaN,S
365,366,0,3,"Adahl, Mr. Mauritz Nils Martin",male,30.0,0,0,C 7076,7.250,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.550,NaN,S
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.600,C2,S

Right now our main is not measure the performance of the model<br>
our main main is to learn about the pipeline here

In [32]:
df.drop(columns =['PassengerId','Name','Ticket','Cabin'],inplace = True)
#we have drop these column becouse the are not important for us

inplace = True :- <br>
inplace = false(default) :-

In [34]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

we are gooing to make a model that will tell  that <br>
he/ she will survive or not on giving class, sex, Age,Sibsp,Parch, fare, Embarked.

In [41]:
# step 1 -> train/test/split
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns =["Survived"]),
                                                 df["Survived"],
                                                 test_size=0.2,
                                                 random_state=42)

In [45]:
x_train.head(2)

     Pclass   Sex   Age  SibSp  Parch  Fare Embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [59]:
y_train.head()

331    0
733    0
382    0
704    0
813    0
Name: Survived, dtype: int64

In [61]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [63]:
# we have null value in Age as well as in the Embarked column

In [69]:
# applying imputation to fil the null value
si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')



x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked = si_embarked.fit_transform(x_train[['Embarked']])


x_test_age = si_age.fit_transform(x_train[['Age']])
x_test_embarked = si_embarked.fit_transform(x_train[['Embarked']])