In [3]:
import pandas as pd
import requests

In [13]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=e47c141b5a5a5101df12ad52991e073f&language=en-US&page=1')

In [19]:
response.json() # explictly converting incoming data to json

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 26.8395,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'title': 'The Shawshank Redemption',
   'video': False,
   'vote_average': 8.716,
   'vote_count': 29654},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 28.7729,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'title': 'The Godfather',
   'video': False,
   'vote_average': 8.687,
   'vote_count': 22397},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 15.6745,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'title': 'The Godfather Part II',
   'video': False,
   'vote_average': 8.571,
   'vote_count': 13550},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 16.463,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'title': "Schindler's List",
   'video': False,
   'vote_average': 8.6,
   'vote_count': 17071},
  {'adult': False,
   'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
   'genre_ids': [18],
   'id': 389,
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 10.5955,
   'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg',
   'release_date': '1957-04-10',
   'title': '12 Angry Men',
   'video': False,
   'vote_average': 8.554,
   'vote_count': 9708},
  {'adult': False,
   'backdrop_path': '/ukfI9QkU1aIhOhKXYWE9n3z1mFR.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 17.7989,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'title': 'Spirited Away',
   'video': False,
   'vote_average': 8.533,
   'vote_count': 17902},
  {'adult': False,
   'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 25.9213,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'title': 'The Dark Knight',
   'video': False,
   'vote_average': 8.526,
   'vote_count': 35104},
  {'adult': False,
   'backdrop_path': '/zQDFHYNVVVp9OAYSixYAG1SyX1l.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 6.6707,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-20',
   'title': 'Dilwale Dulhania Le Jayenge',
   'video': False,
   'vote_average': 8.516,
   'vote_count': 4553},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 19.2365,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'title': 'The Green Mile',
   'video': False,
   'vote_average': 8.504,
   'vote_count': 18801},
  {'adult': False,
   'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 25.442,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'title': 'Parasite',
   'video': False,
   'vote_average': 8.495,
   'vote_count': 20068},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 26.7598,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'title': 'The Lord of the Rings: The Return of the King',
   'video': False,
   'vote_average': 8.493,
   'vote_count': 25963},
  {'adult': False,
   'backdrop_path': '/96hiUXEuYsu4tcnvlaY8tEMFM0m.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 23.786,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'title': 'Pulp Fiction',
   'video': False,
   'vote_average': 8.486,
   'vote_count': 29628},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 20.1392,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'title': 'Your Name.',
   'video': False,
   'vote_average': 8.478,
   'vote_count': 12263},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 10.5297,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-22',
   'title': 'The Good, the Bad and the Ugly',
   'video': False,
   'vote_average': 8.469,
   'vote_count': 9387},
  {'adult': False,
   'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 42.0856,
   'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
   'release_date': '2014-11-05',
   'title': 'Interstellar',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 38777},
  {'adult': False,
   'backdrop_path': '/67HggiWaP9ZLv5sPYmyRV37yAJM.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 13,
   'original_language': 'en',
   'original_title': 'Forrest Gump',
   'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
   'popularity': 20.6246,
   'poster_path': '/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
   'release_date': '1994-06-23',
   'title': 'Forrest Gump',
   'video': False,
   'vote_average': 8.462,
   'vote_count': 29180},
  {'adult': False,
   'backdrop_path': '/gILte6Zd7m1YneIr6MVhh30S9pr.jpg',
   'genre_ids': [18, 80],
   'id': 769,
   'original_language': 'en',
   'original_title': 'GoodFellas',
   'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
   'popularity': 14.5042,
   'poster_path': '/9OkCLM73MIU2CrKZbqiT8Ln1wY2.jpg',
   'release_date': '1990-09-12',
   'title': 'GoodFellas',
   'video': False,
   'vote_average': 8.5,
   'vote_count': 13977},
  {'adult': False,
   'backdrop_path': '/qvZ91FwMq6O47VViAr8vZNQz3WI.jpg',
   'genre_ids': [28, 18],
   'id': 346,
   'original_language': 'ja',
   'original_title': '七人の侍',
   'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.",
   'popularity': 7.8282,
   'poster_path': '/lOMGc8bnSwQhS4XyE1S99uH8NXf.jpg',
   'release_date': '1954-04-26',
   'title': 'Seven Samurai',
   'video': False,
   'vote_average': 8.449,
   'vote_count': 4093},
  {'adult': False,
   'backdrop_path': '/aHaqZpOL7UyVu0nKqp3SMz0o2E1.jpg',
   'genre_ids': [16, 18, 10752],
   'id': 12477,
   'original_language': 'ja',
   'original_title': '火垂るの墓',
   'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.',
   'popularity': 0.0078,
   'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg',
   'release_date': '1988-04-16',
   'title': 'Grave of the Fireflies',
   'video': False,
   'vote_average': 8.442,
   'vote_count': 6330},
  {'adult': False,
   'backdrop_path': '/6aNKD81RHR1DqUUa8kOZ1TBY1Lp.jpg',
   'genre_ids': [35, 18],
   'id': 637,
   'original_language': 'it',
   'original_title': 'La vita è bella',
   'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.',
   'popularity': 9.5629,
   'poster_path': '/mfnkSeeVOBVheuyn2lo4tfmOPQb.jpg',
   'release_date': '1997-12-20',
   'title': 'Life Is Beautiful',
   'video': False,
   'vote_average': 8.44,
   'vote_count': 13767}],
 'total_pages': 532,
 'total_results': 10638}

In [60]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','vote_count','popularity']]

In [64]:
temp_df

,id,title,release_date,vote_count,popularity
0,278,The Shawshank Redemption,1994-09-23,29654,26.8395
1,238,The Godfather,1972-03-14,22397,28.7729
2,240,The Godfather Part II,1974-12-20,13550,15.6745
3,424,Schindler's List,1993-12-15,17071,16.4630
4,389,12 Angry Men,1957-04-10,9708,10.5955
5,129,Spirited Away,2001-07-20,17902,17.7989
6,155,The Dark Knight,2008-07-16,35104,25.9213
7,19404,Dilwale Dulhania Le Jayenge,1995-10-20,4553,6.6707
8,497,The Green Mile,1999-12-10,18801,19.2365
9,496243,Parasite,2019-05-30,20068,25.4420
10,122,The Lord of the Rings: The Return of the King,2003-12-17,25963,26.7598
11,680,Pulp Fiction,1994-09-10,29628,23.7860
12,372058,Your Name.,2016-08-26,12263,20.1392
13,429,"The Good, the Bad and the Ugly",1966-12-22,9387,10.5297
14,157336,Interstellar,2014-11-05,38777,42.0856
15,13,Forrest Gump,1994-06-23,29180,20.6246
16,769,GoodFellas,1990-09-12,13977,14.5042
17,346,Seven Samurai,1954-04-26,4093,7.8282
18,12477,Grave of the Fireflies,1988-04-16,6330,0.0078
19,637,Life Is Beautiful,1997-12-20,13767,9.5629

now doing this process in the loop so that we get a large dataset of the movie

In [67]:
df = pd.DataFrame()

In [87]:
for i in range (1,532) :
    if response.status_code != 200 : # agar koi page per data nahi hai tu errorn nahi dega
        continue
    response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?api_key=e47c141b5a5a5101df12ad52991e073f&language=en-US&page={i}')
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','vote_count','popularity']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [85]:
df

           id                     title release_date  vote_count  popularity
0         278  The Shawshank Redemption   1994-09-23       29654     26.8395
1         238             The Godfather   1972-03-14       22397     28.7729
2         240     The Godfather Part II   1974-12-20       13550     15.6745
3         424          Schindler's List   1993-12-15       17071     16.4630
4         389              12 Angry Men   1957-04-10        9708     10.5955
...       ...                       ...          ...         ...         ...
19995  500904               A Vigilante   2019-03-29         404      4.4329
19996  333386                  The Duel   2016-06-24         369      1.2527
19997  225886                  Sex Tape   2014-07-17        4175      8.6441
19998   82990     Paranormal Activity 4   2012-10-17        1993      2.8538
19999  528085                      2067   2020-10-01         904      1.6701

[20000 rows x 5 columns]

In [91]:
df.shape

(20000, 5)

In [96]:
df.to_csv('my_made_movie_data.csv')